name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install flake8
      - name: Run flake8
        run: flake8 scripts/
        
  experiment-tracking:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run MLflow Experiment
        run: python train_model.py

  data-versioning:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install DVC
        run: pip install dvc

      - name: Track Dataset
        run: |
          dvc add data/dataset.csv
          git add data/dataset.csv.dvc .gitignore
          git commit -m "Track dataset with DVC"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest
        run: pytest tests/

  deploy:
    name: Simulated Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Simulated Deployment Step
        run: echo "Deploying model (simulated)"

